### ISSUE TITLE
有计划升级一下egg-graphql吗?

### ISSUE THREAD

**Issue by yuu2lee4** [eggjs/egg#2862]
现在egg的graphql插件有点儿老了 很多接口都跟apollo2.0不一致了  请问有计划升级一下egg-graphql吗

**Comment by Maledong** [comment]
It's NOT an easy thing by just upgrading from v1.x to 2.x because of a huge BRAKING change between the two versions of Apollo.

Ref: https://github.com/apollographql/apollo-server/issues/1308

**Comment by Maledong** [comment]
After a period of time I've finished upgrading this to the latest version of graphql, which is a BREAKING CHANGE version since v2.x.y. But in order to keep the most of codes as a middle-ware function. I just use the easiest way to cope with the problem. I'll have a check and do submitting when free.

**Comment by Maledong** [comment]
@atian25 : This has been loaded at https://github.com/eggjs/egg-graphql/pull/18 and merged, so this can be closed.
