### ISSUE TITLE
Egg ChangeLog Monthly Feed

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#3354]
Watch https://github.com/eggjs/egg-feed-bot/issues to get notify of Egg && Plugins changelog feeds.

**Comment by Maledong** [comment]
We iterate "Egg" by developing its plug-ins to assign different kinds of functions into the different modules of them.

The master repository of "Egg" itself won't be published frequently, however we may publish its dependent plug-ins weekly because of newly-added features or bug fixes in new versions.

In order to let more developers know when these plug-ins are updated, we now offer you a Bot that will automatically collect information of monthly changes.

Anyone who is interested in this can click the "Watch" button on the right corner, and choose "Releases Only", as we mention you below:

![watch](https://user-images.githubusercontent.com/40081831/50538157-f6d25680-0ba5-11e9-8ffa-4bc5c9011cd6.png)
