### ISSUE TITLE
systemd.service

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3508]
I want to create a `systemd.service` config file , What `type=` is recommended , I think `fork`

**Comment by atian25** [comment]
I'm not familiar with `systemd.service`, as it's docs say, if you're using `egg-script` with `--daemon`, should be` fork`, otherwise, maybe `simple`.

**Comment by sm2017** [comment]
Must I use `ExecStart=yarn run start` or `ExecStart=egg-scripts start --daemon` or not difference?

**Comment by atian25** [comment]
It depends on your npm scripts.

`npm start / yarn start` will fork the real scripts which defined at `pkg.scripts.start`.

so the relations ship of process is:

```bash
└── system
    └── npm
        └── egg-scripts
            └── egg master process
                ├── egg agent process
                ├── egg worker process 1
                ├── egg worker process 2
                ├── ...
                └── egg worker process n
```

if you `pkg.scripts.start = egg-scripts start --daemon`, then after `egg master process` started, the `egg-scripts` will auot exit, then `npm process` will exit too due to it's only child process is exit.

**Comment by sm2017** [comment]
my `pkg.scripts.start = egg-scripts start --daemon` , As `npm` don't forks

I think I cannot use `type=forking` and `ExecStart=yarn run start` , I must use `ExecStart=yarn run start` , What you think ?

**Comment by atian25** [comment]
I'm not sure, I'm not familiar with `systemd.service`.

maybe you could set `pkg.scripts.start = egg-scripts start`, then just use `systemd.service` to monitor `npm process`, it'll remain 2 addition process, but cost is less.
