### ISSUE TITLE
自定义框架内定好的编译流程配置怎样才被上层应用使用呢?

### ISSUE THREAD

**Issue by vincween** [eggjs/egg#411]
需要自己写脚本调用编译流程然后对外提供接口 上层应用调用么?

# #

**Comment by popomore** [comment]
可以跟进 https://github.com/eggjs/egg/issues/241 这个 issue

不知道你具体的场景是什么，编译流程配置只是静态文件？可以在这里先讨论下。

**Comment by atian25** [comment]
麻烦描述下具体的场景

**Comment by vincween** [comment]
sorry, 比如说将各个环境下的webpack配置和发布脚本这些抽离到框架中, 然后再引入上层应用,上层应用可以直接使用和触发这些命令而不需要自己再配置一次吗?

**Comment by vincween** [comment]
现在的想法是自己在框架层提供接口, 接口处理编译构建发布这些操作, 然后应用层再调用, 不知道这样是否合适或者说还有别的方式?

**Comment by popomore** [comment]
你可以把 webpack 包装一层，比如
https://github.com/ant-tool/atool-build，然后编译脚本直接调用，如果有配置可以读取一个
json，不要开放 webpack 的配置。

Vincween <notifications@github.com>于2017年2月19日 周日11:43写道：

现在的想法是自己在框架层提供接口, 接口处理编译构建发布这些操作, 然后应用层再调用, 不知道这样是否合适或者说还有别的方式?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/eggjs/egg/issues/411#issuecomment-280893724>, or mute
the thread

**Comment by dead-horse** [comment]
一般来说，前端资源的构建和发布是独立于整体框架外自成体系的，我们会约定都通过 `npm run build` 执行 npm scripts 中的 build 命令来进行项目的前端构建，至于怎么构建一般不会打包到后端框架中，因为很难在框架层面统一解决所有的构建需求。

- package.json

```json
{
  "scripts": {
    "build": "atool-build"
  }
}
```

**Comment by vincween** [comment]
嗯嗯 对的 这个星期在业务中进行了尝试 但是最后发现 编译构建这个环节的定制需求还是太多了 很难全部满足 所以这一层还是不适合剥离出来放到框架里边 还是应该独立一个自己的模块 多谢耐心提供建议哈
