### ISSUE TITLE
[Feature Request] egg能不能添加把程序打包成一个可执行文件的功能？

### ISSUE THREAD

**Issue by pxim** [eggjs/egg#4399]
## Background
我们给学校，企业定制的软件，不想把源代码给过去，只想给一个可执行文件。

## Proposal
类似exe，pkg之类的？ 类似electron可以打包成一个可执行文件或者安装文件一样。

**Comment by atian25** [comment]
不属于 Egg 自身的职责，直接用 pkg 之类的即可。

**Comment by pxim** [comment]
> 不属于 Egg 自身的职责，直接用 pkg 之类的即可。

其实我想egg集成这个功能的，这样用起来就一体化了，不用每个人都为这个去搞配置，搞的千奇百怪的。
不过如果egg不打算这样的，那只能我们自己去模式了，还是谢谢了。

**Comment by atian25** [comment]
egg 的生态并不一定需要官方全权包揽的。就像 Koa 生态曾经最大的 Router 也不是官方维护的。

你们可以把摸索出的成果开源出来，只要做的好，也会变为事实标准的，加油。

**Comment by pxim** [comment]
> egg 的生态并不一定需要官方全权包揽的。就像 Koa 生态曾经最大的 Router 也不是官方维护的。
> 
> 你们可以把摸索出的成果开源出来，只要做的好，也会变为事实标准的，加油。

好的，谢谢

**Comment by gaoyangy** [comment]
可以看看 electron 高阳阳 邮箱：yangyangae86@gmail.com 签名由 网易邮箱大师 定制 在2020年07月29日 11:29，Peng Xiang 写道： Background 我们给学校，企业定制的软件，不想把源代码给过去，只想给一个可执行文件。 Proposal 类似exe，pkg之类的？ 类似electron可以打包成一个可执行文件或者安装文件一样。 Additional context Add any other context or screenshots about the feature request here. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
