### ISSUE TITLE
中间件里访问不到ctx

### ISSUE THREAD

**Issue by justinli0709** [eggjs/egg#658]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by popomore** [comment]
第一个参数是 ctx

justinli0709 <notifications@github.com>于2017年3月27日 周一11:51写道：


   - *Node Version*:
   - *Egg Version*:
   - *Plugin Name*:
   - *Plugin Version*:
   - *Platform*:

//auth.js
module.exports = () => {
return async(ctx, next) => {
console.log('auth');
console.log(this.ctx);
await next();
console.log(this.ctx);
};
};

ctx为undefined

请问我应该如何写？多谢！

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eggjs/egg/issues/658>, or mute the thread

**Comment by xjchenhao** [comment]
中间件里访问不到ctx，应该怎么写？

**Comment by atian25** [comment]
@xjchenhao 阅读下 https://eggjs.org/zh-cn/basics/objects.html#获取方式-2

**Comment by xjchenhao** [comment]
@atian25 要升级成Node.js 7.6+才行吗？

**Comment by atian25** [comment]
看你的 middleware 是哪一种风格，分别有不同的用法，文档那里不是有示例代码么

**Comment by xjchenhao** [comment]
哦哦 懂了 谢谢🙏
